# Generated by Django 5.2.6 on 2025-09-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BankruptcyCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numer sprawy"
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("consumer", "Upadłość konsumencka"),
                            ("business", "Upadłość przedsiębiorstwa"),
                            ("liquidation", "Upadłość likwidacyjna"),
                            ("arrangement", "Upadłość układowa"),
                        ],
                        max_length=20,
                        verbose_name="Typ upadłości",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparation", "Przygotowanie wniosku"),
                            ("filed", "Wniosek złożony"),
                            ("hearing", "Rozprawa"),
                            ("declared", "Upadłość ogłoszona"),
                            ("ongoing", "W toku"),
                            ("completed", "Zakończona"),
                            ("rejected", "Oddalona"),
                        ],
                        default="preparation",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("court", models.CharField(max_length=200, verbose_name="Sąd")),
                (
                    "judge",
                    models.CharField(blank=True, max_length=100, verbose_name="Sędzia"),
                ),
                (
                    "trustee",
                    models.CharField(blank=True, max_length=100, verbose_name="Syndyk"),
                ),
                (
                    "filing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data złożenia wniosku"
                    ),
                ),
                (
                    "declaration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data ogłoszenia upadłości"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "debt_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Kwota zadłużenia",
                    ),
                ),
                (
                    "assets_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Wartość majątku",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis sprawy")),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notatki wewnętrzne"),
                ),
                (
                    "assigned_lawyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bankruptcy_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przydzielony prawnik",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bankruptcy_cases",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprawa upadłościowa",
                "verbose_name_plural": "Sprawy upadłościowe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BankruptcyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("filing", "Złożenie wniosku"),
                            ("hearing", "Rozprawa"),
                            ("decision", "Postanowienie"),
                            ("creditors_meeting", "Zgromadzenie wierzycieli"),
                            ("asset_sale", "Sprzedaż majątku"),
                            ("distribution", "Podział środków"),
                            ("report", "Sprawozdanie"),
                            ("other", "Inne"),
                        ],
                        max_length=30,
                        verbose_name="Typ wydarzenia",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Data wydarzenia")),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("description", models.TextField(verbose_name="Opis")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publiczne"),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data przypomnienia"
                    ),
                ),
                (
                    "bankruptcy_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="upadlosc.bankruptcycase",
                        verbose_name="Sprawa upadłościowa",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzone przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie",
                "verbose_name_plural": "Wydarzenia",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="ConsumerBankruptcy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "monthly_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Miesięczny dochód",
                    ),
                ),
                (
                    "family_size",
                    models.IntegerField(verbose_name="Liczba osób w rodzinie"),
                ),
                (
                    "has_real_estate",
                    models.BooleanField(
                        default=False, verbose_name="Posiada nieruchomości"
                    ),
                ),
                (
                    "repayment_plan_duration",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Okres planu spłaty (miesiące)",
                    ),
                ),
                (
                    "repayment_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Procent spłaty",
                    ),
                ),
                (
                    "reason_for_debt",
                    models.TextField(verbose_name="Przyczyna zadłużenia"),
                ),
                (
                    "previous_bankruptcy",
                    models.BooleanField(
                        default=False, verbose_name="Poprzednia upadłość"
                    ),
                ),
                (
                    "previous_bankruptcy_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data poprzedniej upadłości"
                    ),
                ),
                (
                    "bankruptcy_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consumer_details",
                        to="upadlosc.bankruptcycase",
                        verbose_name="Sprawa upadłościowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Upadłość konsumencka - szczegóły",
                "verbose_name_plural": "Upadłości konsumenckie - szczegóły",
            },
        ),
        migrations.CreateModel(
            name="Creditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa wierzyciela"),
                ),
                (
                    "creditor_type",
                    models.CharField(
                        choices=[
                            ("bank", "Bank"),
                            ("tax_office", "Urząd Skarbowy"),
                            ("zus", "ZUS"),
                            ("supplier", "Dostawca"),
                            ("employee", "Pracownik"),
                            ("other", "Inny"),
                        ],
                        max_length=50,
                        verbose_name="Typ wierzyciela",
                    ),
                ),
                (
                    "claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Kwota wierzytelności",
                    ),
                ),
                (
                    "claim_category",
                    models.IntegerField(
                        choices=[
                            (1, "Kategoria pierwsza"),
                            (2, "Kategoria druga"),
                            (3, "Kategoria trzecia"),
                            (4, "Kategoria czwarta"),
                        ],
                        verbose_name="Kategoria wierzytelności",
                    ),
                ),
                (
                    "is_secured",
                    models.BooleanField(default=False, verbose_name="Zabezpieczona"),
                ),
                (
                    "security_description",
                    models.TextField(blank=True, verbose_name="Opis zabezpieczenia"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Osoba kontaktowa"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email kontaktowy"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Telefon kontaktowy"
                    ),
                ),
                (
                    "bankruptcy_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditors",
                        to="upadlosc.bankruptcycase",
                        verbose_name="Sprawa upadłościowa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wierzyciel",
                "verbose_name_plural": "Wierzyciele",
                "ordering": ["claim_category", "-claim_amount"],
            },
        ),
    ]
