# Generated by Django 5.2.6 on 2025-09-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("default", "Domyślny"),
                            ("landing", "Landing Page"),
                            ("contact", "Kontakt"),
                            ("about", "O nas"),
                            ("services", "Usługi"),
                        ],
                        default="default",
                        max_length=50,
                        verbose_name="Szablon",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Opublikowana"),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(default=False, verbose_name="Pokaż w menu"),
                ),
                (
                    "menu_order",
                    models.IntegerField(default=0, verbose_name="Kolejność w menu"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta tytuł"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta opis"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta słowa kluczowe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Strona",
                "verbose_name_plural": "Strony",
                "ordering": ["menu_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Nazwa"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tagi",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Nazwa"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cms.category",
                        verbose_name="Kategoria nadrzędna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoria",
                "verbose_name_plural": "Kategorie",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "slug",
                    models.SlugField(max_length=200, unique=True, verbose_name="Slug"),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="Zajawka"
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog/%Y/%m/",
                        verbose_name="Obraz wyróżniający",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Szkic"),
                            ("published", "Opublikowany"),
                            ("archived", "Zarchiwizowany"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data publikacji"
                    ),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Liczba wyświetleń"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Wyróżniony"),
                ),
                (
                    "allow_comments",
                    models.BooleanField(
                        default=True, verbose_name="Zezwól na komentarze"
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta tytuł"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta opis"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta słowa kluczowe"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="cms.category",
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="posts",
                        to="cms.tag",
                        verbose_name="Tagi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Post blogowy",
                "verbose_name_plural": "Posty blogowe",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "author_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Imię autora"
                    ),
                ),
                (
                    "author_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email autora"
                    ),
                ),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Zatwierdzony"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="cms.comment",
                        verbose_name="Odpowiedź na",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="cms.blogpost",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Komentarz",
                "verbose_name_plural": "Komentarze",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="media/%Y/%m/", verbose_name="Plik"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Tekst alternatywny"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Obraz"),
                            ("document", "Dokument"),
                            ("video", "Wideo"),
                            ("other", "Inne"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Typ pliku",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Rozmiar pliku (bytes)"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przesłane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plik mediów",
                "verbose_name_plural": "Pliki mediów",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Avatar",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Bio")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Administrator"),
                            ("editor", "Edytor"),
                            ("author", "Autor"),
                            ("viewer", "Przeglądający"),
                        ],
                        default="viewer",
                        max_length=20,
                        verbose_name="Rola",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Otrzymuj powiadomienia"
                    ),
                ),
                (
                    "dark_mode",
                    models.BooleanField(default=False, verbose_name="Tryb ciemny"),
                ),
                (
                    "language",
                    models.CharField(default="pl", max_length=5, verbose_name="Język"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Użytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil użytkownika",
                "verbose_name_plural": "Profile użytkowników",
            },
        ),
    ]
