# Generated by Django 5.2.6 on 2025-09-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RestructuringCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "case_number",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numer sprawy"
                    ),
                ),
                (
                    "proceeding_type",
                    models.CharField(
                        choices=[
                            (
                                "arrangement_approval",
                                "Postępowanie o zatwierdzenie układu",
                            ),
                            (
                                "accelerated_arrangement",
                                "Przyspieszone postępowanie układowe",
                            ),
                            ("arrangement", "Postępowanie układowe"),
                            ("sanation", "Postępowanie sanacyjne"),
                        ],
                        max_length=30,
                        verbose_name="Rodzaj postępowania",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("preparation", "Przygotowanie"),
                            ("filed", "Wniosek złożony"),
                            ("opened", "Postępowanie otwarte"),
                            ("arrangement_proposed", "Propozycja układowa"),
                            ("voting", "Głosowanie"),
                            ("arrangement_accepted", "Układ przyjęty"),
                            ("arrangement_approved", "Układ zatwierdzony"),
                            ("execution", "Wykonanie układu"),
                            ("completed", "Zakończone"),
                            ("discontinued", "Umorzone"),
                        ],
                        default="preparation",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                ("court", models.CharField(max_length=200, verbose_name="Sąd")),
                (
                    "judge_commissioner",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sędzia-komisarz"
                    ),
                ),
                (
                    "court_supervisor",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Nadzorca sądowy"
                    ),
                ),
                (
                    "restructuring_advisor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Doradca restrukturyzacyjny",
                    ),
                ),
                (
                    "filing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data złożenia wniosku"
                    ),
                ),
                (
                    "opening_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data otwarcia postępowania"
                    ),
                ),
                (
                    "arrangement_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zatwierdzenia układu"
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zakończenia"
                    ),
                ),
                (
                    "total_debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Całkowite zadłużenie",
                    ),
                ),
                (
                    "restructured_debt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Zadłużenie objęte układem",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis sprawy")),
                (
                    "restructuring_plan",
                    models.TextField(blank=True, verbose_name="Plan restrukturyzacji"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notatki wewnętrzne"),
                ),
                (
                    "assigned_lawyer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restructuring_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przydzielony prawnik",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restructuring_cases",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprawa restrukturyzacyjna",
                "verbose_name_plural": "Sprawy restrukturyzacyjne",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ArrangementProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "version",
                    models.IntegerField(default=1, verbose_name="Wersja propozycji"),
                ),
                (
                    "reduction_percentage",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Procent redukcji"
                    ),
                ),
                (
                    "payment_installments",
                    models.IntegerField(verbose_name="Liczba rat"),
                ),
                (
                    "payment_period_months",
                    models.IntegerField(verbose_name="Okres spłaty (miesiące)"),
                ),
                (
                    "grace_period_months",
                    models.IntegerField(
                        default=0, verbose_name="Okres karencji (miesiące)"
                    ),
                ),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Oprocentowanie",
                    ),
                ),
                (
                    "special_conditions",
                    models.TextField(blank=True, verbose_name="Warunki szczególne"),
                ),
                ("creditor_groups", models.TextField(verbose_name="Grupy wierzycieli")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
                (
                    "submission_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data złożenia"
                    ),
                ),
                (
                    "restructuring_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="restrukturyzacja.restructuringcase",
                        verbose_name="Sprawa restrukturyzacyjna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Propozycja układowa",
                "verbose_name_plural": "Propozycje układowe",
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="RestructuringCreditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Nazwa wierzyciela"),
                ),
                (
                    "creditor_group",
                    models.IntegerField(
                        choices=[
                            (1, "Grupa I - Pracownicy"),
                            (2, "Grupa II - ZUS i Urząd Skarbowy"),
                            (3, "Grupa III - Zabezpieczeni"),
                            (4, "Grupa IV - Pozostali"),
                            (5, "Grupa V - Powiązani"),
                        ],
                        verbose_name="Grupa wierzycieli",
                    ),
                ),
                (
                    "original_claim",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Pierwotna wierzytelność",
                    ),
                ),
                (
                    "verified_claim",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Wierzytelność po weryfikacji",
                    ),
                ),
                (
                    "restructured_claim",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Wierzytelność po układzie",
                    ),
                ),
                (
                    "voting_power",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Siła głosu (%)",
                    ),
                ),
                (
                    "vote_cast",
                    models.CharField(
                        choices=[
                            ("for", "Za"),
                            ("against", "Przeciw"),
                            ("abstain", "Wstrzymał się"),
                            ("not_voted", "Nie głosował"),
                        ],
                        default="not_voted",
                        max_length=10,
                        verbose_name="Głos",
                    ),
                ),
                (
                    "is_disputed",
                    models.BooleanField(default=False, verbose_name="Sporna"),
                ),
                (
                    "dispute_description",
                    models.TextField(blank=True, verbose_name="Opis sporu"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Osoba kontaktowa"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "restructuring_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creditors",
                        to="restrukturyzacja.restructuringcase",
                        verbose_name="Sprawa restrukturyzacyjna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wierzyciel restrukturyzacyjny",
                "verbose_name_plural": "Wierzyciele restrukturyzacyjni",
                "ordering": ["creditor_group", "-original_claim"],
            },
        ),
        migrations.CreateModel(
            name="RestructuringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("filing", "Złożenie wniosku"),
                            ("opening", "Otwarcie postępowania"),
                            ("creditors_list", "Złożenie spisu wierzytelności"),
                            ("arrangement_proposal", "Złożenie propozycji układowej"),
                            ("creditors_meeting", "Zgromadzenie wierzycieli"),
                            ("voting", "Głosowanie"),
                            ("court_hearing", "Rozprawa"),
                            ("arrangement_approval", "Zatwierdzenie układu"),
                            ("report", "Sprawozdanie"),
                            ("payment", "Płatność"),
                            ("other", "Inne"),
                        ],
                        max_length=30,
                        verbose_name="Typ wydarzenia",
                    ),
                ),
                ("event_date", models.DateTimeField(verbose_name="Data wydarzenia")),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("description", models.TextField(verbose_name="Opis")),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="Publiczne"),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(default=False, verbose_name="Obowiązkowe"),
                ),
                (
                    "reminder_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data przypomnienia"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Utworzone przez",
                    ),
                ),
                (
                    "restructuring_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="restrukturyzacja.restructuringcase",
                        verbose_name="Sprawa restrukturyzacyjna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wydarzenie restrukturyzacyjne",
                "verbose_name_plural": "Wydarzenia restrukturyzacyjne",
                "ordering": ["-event_date"],
            },
        ),
        migrations.CreateModel(
            name="ArrangementPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                ("installment_number", models.IntegerField(verbose_name="Numer raty")),
                ("due_date", models.DateField(verbose_name="Termin płatności")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Kwota"
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Zapłacona"),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data zapłaty"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Zapłacona kwota",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Uwagi")),
                (
                    "restructuring_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="restrukturyzacja.restructuringcase",
                        verbose_name="Sprawa restrukturyzacyjna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Płatność układowa",
                "verbose_name_plural": "Płatności układowe",
                "ordering": ["due_date", "installment_number"],
                "unique_together": {("restructuring_case", "installment_number")},
            },
        ),
    ]
