# Generated by Django 5.2.6 on 2025-09-16 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Imię i nazwisko"),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("partner", "Partner"),
                            ("lawyer", "Radca prawny"),
                            ("attorney", "Adwokat"),
                            ("advisor", "Doradca restrukturyzacyjny"),
                            ("specialist", "Specjalista"),
                        ],
                        max_length=50,
                        verbose_name="Stanowisko",
                    ),
                ),
                ("bio", models.TextField(verbose_name="Biografia")),
                ("specializations", models.TextField(verbose_name="Specjalizacje")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="team/", verbose_name="Zdjęcie"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("linkedin", models.URLField(blank=True, verbose_name="LinkedIn")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Kolejność wyświetlania"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Członek zespołu",
                "verbose_name_plural": "Członkowie zespołu",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nazwa/Imię i nazwisko"
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("individual", "Osoba fizyczna"),
                            ("company", "Przedsiębiorstwo"),
                        ],
                        max_length=20,
                        verbose_name="Typ klienta",
                    ),
                ),
                (
                    "nip",
                    models.CharField(blank=True, max_length=20, verbose_name="NIP"),
                ),
                (
                    "regon",
                    models.CharField(blank=True, max_length=20, verbose_name="REGON"),
                ),
                (
                    "krs",
                    models.CharField(blank=True, max_length=20, verbose_name="KRS"),
                ),
                (
                    "pesel",
                    models.CharField(blank=True, max_length=11, verbose_name="PESEL"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("address", models.CharField(max_length=200, verbose_name="Adres")),
                ("city", models.CharField(max_length=100, verbose_name="Miasto")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Kod pocztowy"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notatki")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Klient",
                "verbose_name_plural": "Klienci",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("court_decision", "Postanowienie sądu"),
                            ("application", "Wniosek"),
                            ("financial_report", "Sprawozdanie finansowe"),
                            ("contract", "Umowa"),
                            ("other", "Inne"),
                        ],
                        max_length=50,
                        verbose_name="Typ dokumentu",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="documents/%Y/%m/", verbose_name="Plik"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Opis")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="core.client",
                        verbose_name="Klient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Przesłane przez",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dokument",
                "verbose_name_plural": "Dokumenty",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data modyfikacji"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                ("excerpt", models.TextField(max_length=500, verbose_name="Zajawka")),
                ("content", models.TextField(verbose_name="Treść")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="news/%Y/%m/", verbose_name="Obraz"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Opublikowany"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data publikacji"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bankruptcy", "Upadłość"),
                            ("restructuring", "Restrukturyzacja"),
                            ("law_changes", "Zmiany w prawie"),
                            ("court_rulings", "Orzecznictwo"),
                            ("analysis", "Analizy"),
                        ],
                        max_length=50,
                        verbose_name="Kategoria",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aktualność",
                "verbose_name_plural": "Aktualności",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
    ]
